sudo: required
dist: trusty
# everything is driven by the test.sh, so the language doesn't really
# matter, it just controls the default install/script/etc. steps on
# travis.
language: cpp
os: osx
osx_image: xcode8.3
script:
  - ./tests.sh $CONFIG
env:
  - CONFIG=cpp
  - CONFIG=cpp_distcheck
  # Testing go requires installing golang, currently travis.sh is doing that
  #   with apt-get which doesn't work on OS X.
  # It's nontrivial to programmatically install a new JDK from the command
  #   line on OS X, so we rely on testing on Linux for Java code.
  - CONFIG=javascript
  # iOS build log was starting to choke travis UI, so split to cover the
  # Xcode Debug and Release Configurations independently.
  - CONFIG=objectivec_ios_debug
  - CONFIG=objectivec_ios_release
  - CONFIG=objectivec_osx
  - CONFIG=objectivec_cocoapods_integration
  - CONFIG=python
  - CONFIG=python_cpp
  - CONFIG=php5.6_mac
  - CONFIG=php7.0_mac
matrix:
  include:
    # The dotnet environment requires Ubuntu 14.04 or 16.04. This
    # configuration is effectively an "extra" one, outside the
    # autogenerated matrix.
    - os: linux
      env: CONFIG=csharp
      language: csharp
      dist: trusty
      dotnet: 1.0.1
      mono: none
    # This test is kept on travis because it doesn't play nicely with other
    # tests on jenkins running in parallel.
    - os: linux
      env: CONFIG=cpp_distcheck
    # The Java compatibility test currently only runs on Linux because it will
    # fetch pre-built Linux protoc binaries in the test.
    - os: linux
      env: CONFIG=java_compatibility
    # The Python compatibility test currently only runs on Linux because it will
    # fetch pre-built Linux protoc binaries in the test.
    - os: linux
      env: CONFIG=python_compatibility
  allow_failures:
    # https://github.com/google/protobuf/issues/1253 - Started failing when
    # we moved to an OS X image that is 10.11.
    - os: osx
      env: CONFIG=python_cpp
    # Mark the iOS test as flakey as xcodebuild some times fails to start the
    # iOS Simulator.
    - os: osx
      env: CONFIG=objectivec_ios_debug
    - os: osx
      env: CONFIG=objectivec_ios_release
notifications:
  email: false
