env:
  global:
      - REPO_DIR=protobuf
      - BUILD_COMMIT=v3.5.2
      - BUILD_VERSION=3.5.2.post1
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - MACOSX_DEPLOYMENT_TARGET=10.9
      - WHEELHOUSE_UPLOADER_USERNAME=protobuf-wheel-test
      - secure:
          "SyS97P0pulx8rCNLHIxqUFBfovzKqQC5gYSV0qUMFm+dRcZH80Z8vzP0ihmibu2CmFV79Vf1esckvCBOV7difWruT3VVMj2Tdf2gMRk6kjai5YUP+3UPT8RMbkVTUKl0qII0ZPul0G4dHuqtJf5Mq2Gmco+3NZMg6Vr9VrZbBoY="

language: python
# Default Python version is usually 2.7
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5
  include:
    - os: linux
      env: MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.3
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.4
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - MB_PYTHON_VERSION=3.3
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - MB_PYTHON_VERSION=3.4
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR/python $PLAT

script:
    - install_run $PLAT

after_success:
    - pip install twine
    - pip install pyOpenSSL ndg-httpsclient pyasn1
    - source deploy_travis.sh
    - deploy
